# Generated by Django 5.1.1 on 2024-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Soyadınız'),
        ),
        migrations.AlterField(
            model_name='about',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300, null=True, verbose_name='Kendinden Bahset'),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Adınız'),
        ),
        migrations.AlterField(
            model_name='about',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='about',
            name='work_status',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='İş Statüsü'),
        ),
    ]
