# Generated by Django 5.1.1 on 2024-09-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about_surname_alter_about_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Yetenek Adı')),
                ('percentage', models.IntegerField(default=0, verbose_name='Yüzde')),
                ('proccess_color', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Renk')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Oluşturulma Tarihi')),
            ],
        ),
    ]
