# Generated by Django 5.1.1 on 2024-09-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_services_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='ServicesName',
        ),
    ]
