# Generated by Django 5.1.1 on 2024-09-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_services_servicesname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name='Resim')),
                ('link', models.URLField(verbose_name='Link')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Projelerim',
                'verbose_name_plural': 'Projelerim',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['name'], 'verbose_name': 'Hakkımda Ayarları', 'verbose_name_plural': 'Hakkımda Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['name'], 'verbose_name': 'Resim Ayarları', 'verbose_name_plural': 'Resim Ayarları'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title'], 'verbose_name': 'Yetkinliklerim Detay Alanı', 'verbose_name_plural': 'Yetkinliklerim Detay Alanı'},
        ),
        migrations.AlterModelOptions(
            name='servicesname',
            options={'ordering': ['name'], 'verbose_name': 'Yeteneklerim', 'verbose_name_plural': 'Yeteneklerim'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'Yetkinlikler Ayarları', 'verbose_name_plural': 'Yetkinlikler Ayarları'},
        ),
    ]
