# Generated by Django 5.1.1 on 2024-09-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_projects_alter_about_options_alter_images_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.TextField(blank=True, default='', max_length=300, null=True, verbose_name='Alıntılar')),
                ('quotationer', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Alıntı Sahibi')),
            ],
            options={
                'verbose_name': 'Alıntılar',
                'verbose_name_plural': 'Alıntılar',
                'ordering': ['quotes'],
            },
        ),
    ]
