# Generated by Django 5.1.1 on 2024-09-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_documant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documant',
            options={'ordering': ['slug'], 'verbose_name': 'Dökümanlar', 'verbose_name_plural': 'Dökümanlar'},
        ),
        migrations.RemoveField(
            model_name='documant',
            name='name',
        ),
        migrations.AddField(
            model_name='documant',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, verbose_name='Slug'),
        ),
    ]
