# Generated by Django 5.1.1 on 2024-09-10 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_documant_options_remove_documant_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documant',
            new_name='Document',
        ),
    ]
